const enemies = [
    {
    name: 'General Graardor',
    killsph: 20,
    rolls: 2,
    drops: [
            {
                name: 'Big bones', 
                link: 'Big_bones',
                id: 532,
                dropAmount: [1, 1], 
                rarity: 100
            },
            {
                name: 'Rune 2h sword',
                link: 'Rune_2h_sword',
                id: 1319,
                dropAmount: [1, 1], 
                rarity: 2/21
            },
            {
                name: 'Rune pickaxe', 
                link: 'Rune_pickaxe', 
                id: 1275,
                dropAmount: [1, 1], 
                rarity: 2/21
            },
            {
                name: 'Rune longsword',
                link: 'Rune_longsword', 
                id: 1303,
                dropAmount: [1, 1],
                rarity: 2/21,
            },
            {
                name: 'Rune platebody',
                link: 'Rune_platebody', 
                id: 1127,
                dropAmount: [1, 1],
                rarity:  2/21,
            },
            {
                name: 'Bandos chestplate',
                link: 'Bandos_chestplate',
                id: 11832,
                dropAmount: [1, 1],
                rarity: 1/384,
            },
            {
                name: 'Bandos tassets',
                link: 'Bandos_tassets',
                id: 11834,
                dropAmount: [1, 1],
                rarity: 1/384,
            },
            {
                name: 'Bandos boots',
                link: 'Bandos_boots',
                id: 11836,
                dropAmount: [1, 1],
                rarity: 1/384,
            },
            {
                name: 'Nature rune',
                link: 'Nature_rune',
                id: 561,
                dropAmount: [40, 60],
                rarity: 1/25,
            }, 
            {
                name: 'Adamantite ore',
                link: 'Adamantite_ore',
                id: 449,
                dropAmount: [15, 20],
                rarity: 2/21,
            }, 
            {
                name: 'Coal',
                link: 'Coal',
                id: 453,
                dropAmount: [115, 120],
                rarity: 1/10,
            }, 
            {
                name: 'Coins',
                link: 'Coins',
                dropAmount: [19581, 21000],
                rarity: 1/10,
                price: 1,
            }, 
            {
                name: 'Snapdragon seed',
                link: 'Snapdragon_seed',
                id: 5300,
                dropAmount: [1, 1],
                rarity: 1/25,
            }, 
            {
                name: 'Magic log',
                link: 'Magic_log',
                id: 1513,
                dropAmount: [15, 20],
                rarity: 1/25,
            }, 
            {
                name: 'Super restore(4)',
                link: 'Super_restore4',
                id: 3024,
                dropAmount: [3, 3],
                rarity: 1/25,
            }, 
            {
                name: 'Grimy snapdragon',
                link: 'Grimy_snapdragon',
                id: 3051,
                dropAmount: [3, 3],
                rarity: 1/25,
            }, 
            {
                name: 'Clue scroll (elite)',
                link: 'Clue_scroll',
                dropAmount: [1, 1],
                rarity: 1/250,
            }, 
            {
                name: 'Godsword shard 1',
                link: 'Godsword_shard_1',
                id: 11818,
                dropAmount: [1, 1],
                rarity: 1/256,
            }, 
            {
                name: 'Godsword shard 2',
                link: 'Godsword_shard_2',
                id: 11820,
                dropAmount: [1, 1],
                rarity: 1/256,
            }, 
            {
                name: 'Godsword shard 3',
                link: 'Godsword_shard_3',
                id: 11822,
                dropAmount: [1, 1],
                rarity: 1/256,
            },
            {
                name: 'Long bone',
                link: 'Long_bone',
                dropAmount: [1, 1],
                rarity: 1/400,
            },
            {
                name: 'Bandos hilt',
                link: 'Bandos_hilt',
                id: 11812,
                dropAmount: [1, 1],
                rarity: 1/508,
            },
            {
                name: 'Pet general graardor',
                link: `Pet_general_graardor`,
                dropAmount: [1, 1],
                rarity: 1/5000,
            },
            {
                name: 'Rare drop table',
                link: 'Rare_drop_table',
                dropAmount: [1, 1],
                rarity: 1/127,
            },
        ]
    },
    {
    name: `Kree'arra`,
    killsph: 20,
    rolls: 3,
    drops: [
            {
                name: 'Big bones', 
                link: 'Big_bones',
                id: 532,
                dropAmount: [1, 1], 
                rarity: 100
            },
            {
                name: 'Feather', 
                link: 'Feather',
                id: 314,
                dropAmount: [1, 15], 
                rarity: 100
            },
            {
                name: 'Rune sword', 
                link: 'Rune_sword',
                id: 1289,
                dropAmount: [1, 1], 
                rarity: 1/406
            },
            {
                name: 'Rune crossbow', 
                link: 'Rune_croosbow',
                id: 9185,
                dropAmount: [1, 1], 
                rarity: 2/21
            },
            {
                name: `Black d'hide`,
                link: 'Black_dhide',
                id: 2503,
                dropAmount: [1, 1],
                rarity: 2/21,
            },
            {
                name: 'Armadyl helmet',
                link: 'Armadyl_helmet',
                id: 11826,
                dropAmount: [1, 1],
                rarity:  1/384,
            },
            {
                name: 'Armadyl chestplate',
                link: 'Armadyl_chestplate',
                id: 11828,
                dropAmount: [1, 1],
                rarity: 1/384,
            },
            {
                name: 'Armadyl chainskirt',
                link: 'Armadyl_chainskirt',
                id: 11830,
                dropAmount: [1, 1],
                rarity: 1/384,
            },
            {
                name: 'Bandos boots',
                link: 'Bandos_boots',
                id: 11836,
                dropAmount: [1, 1],
                rarity: 1/384,
            },
            {
                name: 'Runite bolts',
                link: 'Runite_bolts',
                id: 9144,
                dropAmount: [18, 25],
                rarity: 2/21,
            }, 
            {
                name: 'Mind rune',
                link: 'Mind_rune',
                id: 558,
                dropAmount: [500, 601],
                rarity: 1/64, 
            }, 
            {
                name: 'Rune arrow',
                link: 'Rune_arrow',
                id: 892,
                dropAmount: [100, 105],
                rarity: 1/64, 
            }, 
            {
                name: 'Dragonstone bolts(e)',
                link: 'Dragonstone_boltse',
                id: 9244,
                dropAmount: [5, 15],
                rarity: 1/64,
            }, 
            {
                name: 'Coins',
                link: 'Coins',
                dropAmount: [18000, 21000],
                rarity: 2/21,
                price: 1,
            }, 
            {
                name: 'Rare drop table',
                link: 'Rare_drop_table',
                dropAmount: [1, 1],
                rarity: 8/127,
            }, 
            {
                name: 'Dwarf weed',
                link: 'Dwarf_weed',
                id: 267,
                dropAmount: [5, 22],
                rarity: 2/21,
            }, 
            {
                name: 'Dwarf weed seed',
                link: 'Dwarf_weed_seed',
                id: 5303,
                dropAmount: [3, 3],
                rarity: 2/21,
            }, 
            {
                name: 'Ranging potion(3)',
                link: 'Ranging_potion',
                id: 169,
                dropAmount: [3, 3],
                rarity: 1/64,
            }, 
            {
                name: 'Super defence(3)',
                link: 'Super_defence',
                id: 163,
                dropAmount: [3, 3],
                rarity: 1/64,
            }, 
            {
                name: 'Crystal key',
                link: 'Crystal_key',
                id: 989,
                dropAmount: [3, 3],
                rarity: 1/64,
            }, 
            {
                name: 'Yew seed',
                link: 'Yew_seed',
                id: 5315,
                dropAmount: [1, 1],
                rarity: 1/128, 
            }, 
            {
                name: 'Clue scroll (elite)',
                link: 'Clue_scroll',
                dropAmount: [1, 1],
                rarity: 1/250,
            }, 
            {
                name: 'Godsword shard 1',
                link: 'Godsword_shard_1',
                id: 11818,
                dropAmount: [1, 1],
                rarity: 1/256,
            }, 
            {
                name: 'Godsword shard 2',
                link: 'Godsword_shard_2',
                id: 11820,
                dropAmount: [1, 1],
                rarity: 1/256,
            }, 
            {
                name: 'Godsword shard 3',
                link: 'Godsword_shard_3',
                id: 11822,
                dropAmount: [1, 1],
                rarity: 1/256,
            },
            {
                name: 'Long bone',
                link: 'Long_bone',
                dropAmount: [1, 1],
                rarity: 1/400,
            },
            {
                name: 'Armadyl hilt',
                link: 'Armadyl_hilt',
                id: 11810,
                dropAmount: [1, 1],
                rarity: 1/508,
            },
            {
                name: `Pet kree'arra`,
                link: `Pet_kree'arra`,
                dropAmount: [1, 1],
                rarity: 1/5000,
            },
            {
                name: `Curved bone`,
                link: 'Curved_bone',
                dropAmount: [1, 1],
                rarity: 1/5000,
            },
        ]
    },
    {
    name: `Kril Tsutsaroth`,
    killsph: 20,
    rolls: 2,
    drops: [
            {
                name: 'Ashes', 
                link: `Ashes`,
                dropAmount: [1, 1], 
                rarity: 100,
                price: 1,
            },
            {
                name: 'Adamant arrow(p++)',
                link: 'Adamant arrowp',
                id: 5626,
                dropAmount: [295, 300], 
                rarity: 2/21
            },
            {
                name: 'Rune scimitar',
                link: 'Rune_scimitar',
                id: 1333,
                dropAmount: [1, 1], 
                rarity: 1/64
            },
            {
                name: `Dragon dagger(p++)`,
                link: `Dragon dagger`,
                id: 5698,
                dropAmount: [1, 1],
                rarity: 1/64,
            },
            {
                name: 'Steam battlestaff',
                link: 'Steam_battlestaff',
                id: 11787,
                dropAmount: [1, 1],
                rarity:  1/128,
            },
            {
                name: 'Zamorakian spear',
                link: 'Zamorakian_spear',
                id: 11824,
                dropAmount: [1, 1],
                rarity: 1/128,
            },
            {
                name: 'Rune sword',
                link: 'Rune_sword',
                id: 1289,
                dropAmount: [1, 1],
                rarity: 1/406,
            },
            {
                name: 'Staff of the dead',
                link: 'Staff_of_the_dead',
                id: 11791,
                dropAmount: [1, 1],
                rarity: 1/508,
            },
            {
                name: 'Rune platelegs',
                link: 'Rune_platelegs',
                id: 1079,
                dropAmount: [1, 1],
                rarity: 2/21,
            }, 
            {
                name: 'Adamant platebody',
                name: 'Adamant_platebody',
                id: 1123,
                dropAmount: [1, 1],
                rarity: 2/21,
            }, 
            {
                name: 'Super attack(3)',
                link: 'Super_attack',
                id: 145,
                dropAmount: [3, 3],
                rarity: 2/21,
            }, 
            {
                name: 'Super strength(3)',
                link: 'Super_strength',
                id: 157,
                dropAmount: [3, 3],
                rarity: 2/21,
            }, 
            {
                name: 'Super restore(3)',
                link: 'Super_restore',
                id: 3026,
                dropAmount: [3, 3],
                rarity: 2/21,
            }, 
            {
                name: 'Zamorak brew(3)',
                link: 'Zamorak_brew',
                id: 189,
                dropAmount: [3, 3],
                rarity: 2/21,
            }, 
            {
                name: 'Death rune',
                link: 'Death_rune',
                id: 560,
                dropAmount: [120, 125],
                rarity: 2/21,
            }, 
            {
                name: 'Coins',
                link: 'Coins',
                dropAmount: [19362, 20073],
                rarity: 2/21,
                price: 1,
            }, 
            {
                name: 'Rare drop table',
                link: 'Rare_drop_table',
                dropAmount: [1, 1],
                rarity: 8/127,
            }, 
            {
                name: 'Blood rune',
                name: 'Blood_rune',
                id: 565,
                dropAmount: [80, 90],
                rarity: 1/64,
            }, 
            {
                name: 'Grimy lantadyme',
                link: 'Grimy_lantadyme',
                id: 2485,
                dropAmount: [7, 13],
                rarity: 1/64,
            }, 
            {
                name: 'Lantadyme seed',
                link: 'Lantadyme_seed',
                id: 5302,
                dropAmount: [3, 3],
                rarity: 1/64, 
            }, 
            {
                name: 'Clue scroll (elite)',
                link: 'Clue_scroll',
                dropAmount: [1, 1],
                rarity: 1/250,
            }, 
            {
                name: 'Godsword shard 1',
                link: 'Godsword_shard_1',
                id: 11818,
                dropAmount: [1, 1],
                rarity: 1/256,
            }, 
            {
                name: 'Godsword shard 2',
                link: 'Godsword_shard_2',
                id: 11820,
                dropAmount: [1, 1],
                rarity: 1/256,
            }, 
            {
                name: 'Godsword shard 3',
                link: 'Godsword_shard_3',
                id: 11822,
                dropAmount: [1, 1],
                rarity: 1/256,
            },
            {
                name: 'Long bone',
                link: 'Long_bone',
                dropAmount: [1, 1],
                rarity: 1/400,
            },
            {
                name: 'Zamorak hilt',
                link: 'Zamorak_hilt',
                id: 11816,
                dropAmount: [1, 1],
                rarity: 1/508,
            },
            {
                name: `Pet k'ril tsutsaroth`,
                link: `Pet_k'ril_tsutsaroth`,
                dropAmount: [1, 1],
                rarity: 1/5000,
            },
            {
                name: `Curved bone`,
                link: 'Curved_bone',
                dropAmount: [1, 1],
                rarity: 1/5000,
            },
        ]
    },
    {
    name: `Commander Zilyana`,
    killsph: 20,
    rolls: 2,
    drops: [
            {
                name: 'Bones',
                link: 'Bones',
                id: 526,
                dropAmount: [1, 1], 
                rarity: 100
            },
            {
                name: 'Saradomin sword',
                link: 'Saradomin sword',
                id: 11838,
                dropAmount: [1, 1], 
                rarity: 1/127
            },
            {
                name: 'Armadyl crossbow', 
                link: 'Armadyl_crossbow', 
                id: 11785,
                dropAmount: [1, 1], 
                rarity: 1/508
            },
            {
                name: `Rune sword`,
                link: `Rune_sword`,
                id: 1289,
                dropAmount: [1, 1],
                rarity: 1/406,
            },
            {
                name: 'Rune dart',
                link: `Rune_dart`,
                id: 811,
                dropAmount: [35, 40],
                rarity:  2/21,
            },
            {
                name: 'Law rune',
                link: 'Law_rune',
                id: 563,
                dropAmount: [95, 105],
                rarity: 2/21,
            },
            {
                name: 'Rune plateskirt',
                link: 'Rune_plateskirt',
                id: 1093,
                dropAmount: [1, 1],
                rarity: 2/21,
            },
            {
                name: 'Adamant platebody',
                link: 'Adamant_platebody',
                id: 1123,
                dropAmount: [1, 1],
                rarity: 1/64,
            },
            {
                name: 'Rune kiteshield',
                link: 'Rune_kiteshield',
                id: 1201,
                dropAmount: [1, 1],
                rarity: 1/64,
            }, 
            {
                name: 'Grimy ranarr weed',
                link: 'Grimy_ranarr_weed',
                id: 207,
                dropAmount: [5, 5],
                rarity: 2/21,
            }, 
            {
                name: 'Ranarr seed',
                link: 'Ranarr_seed',
                id: 5295,
                dropAmount: [2, 2],
                rarity: 2/21,
            }, 
            {
                name: 'Prayer potion(4)',
                link: 'Prayer_potion',
                id: 2434,
                dropAmount: [3, 3],
                rarity: 8/127,
            }, 
            {
                name: 'Saradomin brew(3)',
                link: 'Saradomin_brew',
                id: 6687,
                dropAmount: [3, 3],
                rarity: 6/127,
            }, 
            {
                name: 'Super restore(4)',
                link: 'Super_restore',
                id: 3024,
                dropAmount: [3, 3],
                rarity: 6/127,
            },
            {
                name: 'Super defence(4)',
                link: 'Super_defence',
                id: 2442,
                dropAmount: [3, 3],
                rarity: 6/127,
            }, 
            {
                name: 'Magic potion(3)',
                name: 'Magic_potion',
                id: 3042,
                dropAmount: [3, 3],
                rarity: 6/127,
            }, 
            {
                name: 'Magic seed',
                link: 'Magic_seed',
                id: 5316,
                dropAmount: [1, 1],
                rarity: 1/128,
            }, 
            {
                name: 'Coins',
                link: 'Coins',
                dropAmount: [19362, 20073],
                rarity: 2/21,
                price: 1,
            }, 
            {
                name: 'Diamond',
                link: 'Diamond',
                id: 1601,
                dropAmount: [6, 6],
                rarity: 1/64,
            }, 
            {
                name: 'Rare drop table',
                link: 'Rare_drop_table',
                dropAmount: [1, 1],
                rarity: 8/127,
            }, 
            {
                name: `Saradomin's light`,
                link: `Saradomins_light`,
                id: 13256,
                dropAmount: [1, 1],
                rarity: 1/254,
            }, 
            {
                name: 'Clue scroll (elite)',
                link: 'Clue_scroll',
                dropAmount: [1, 1],
                rarity: 1/250,
            }, 
            {
                name: 'Godsword shard 1',
                link: 'Godsword_shard_1',
                id: 11818,
                dropAmount: [1, 1],
                rarity: 1/256,
            }, 
            {
                name: 'Godsword shard 2',
                link: 'Godsword_shard_2',
                id: 11820,
                dropAmount: [1, 1],
                rarity: 1/256,
            }, 
            {
                name: 'Godsword shard 3',
                link: 'Godsword_shard_3',
                id: 11822,
                dropAmount: [1, 1],
                rarity: 1/256,
            },
            {
                name: 'Saradomin hilt',
                link: 'Saradomin_hilt',
                id: 11814,
                dropAmount: [1, 1],
                rarity: 1/508,
            },
            {
                name: `Pet zilyana`,
                link: `Pet_zilyana`,
                dropAmount: [1, 1],
                rarity: 1/5000,
            },
        ]
    },
    {
    name: `Giant Mole`,
    killsph: 20,
    rolls: 4,
    drops: [
            {
                name: 'Big bones', 
                link: 'Big_bones', 
                id: 532,
                dropAmount: [1, 1], 
                rarity: 100
            },
            {
                name: 'Mole claw', 
                link: 'Mole_claw', 
                id: 7416,
                dropAmount: [1, 1], 
                rarity: 100
            },
            {
                name: 'Mole skin', 
                link: 'Mole_skin',
                id: 7418,
                dropAmount: [1, 3], 
                rarity: 100
            },
            {
                name: 'Air rune',
                link: 'Air_rune',
                id: 556,
                dropAmount: [105, 105], 
                rarity: 2/21
            },
            {
                name: `Fire rune`,
                link: 'Fire_rune',
                id: 554,
                dropAmount: [105, 105],
                rarity: 2/21,
            },
            {
                name: 'Blood rune',
                link: 'Blood_rune',
                id: 565,
                dropAmount: [15, 15],
                rarity:  2/21,
            },
            {
                name: 'Death rune',
                link: 'Death_rune',
                id: 560,
                dropAmount: [7, 7],
                rarity: 1/128,
            },
            {
                name: 'Law rune',
                link: 'Law_rune',
                id: 563,
                dropAmount: [15, 15],
                rarity: 1/64,
            },
            {
                name: 'Iron arrow',
                link: 'Iron_arrow',
                id: 884,
                dropAmount: [690, 690],
                rarity: 1/64,
            },
            {
                name: 'Adamant longsword',
                link: 'Adamant_longsword',
                id: 1301,
                dropAmount: [1, 1],
                rarity: 2/21,
            }, 
            {
                name: 'Mithril axe',
                link: 'Mithril_axe',
                id: 1355,
                dropAmount: [1, 1],
                rarity: 2/21,
            }, 
            {
                name: 'Mithril battleaxe',
                link: 'Mithril_battleaxe',
                id: 1369,
                dropAmount: [1, 1],
                rarity: 2/21,
            }, 
            {
                name: 'Mithril platebody',
                link: 'Mithril_platebody',
                id: 1121,
                dropAmount: [1, 1],
                rarity: 2/21,
            }, 
            {
                name: 'Rune med helm',
                link: 'Rune_med_helm',
                id: 1147,
                dropAmount: [1, 1],
                rarity: 1/64,
            }, 
            {
                name: 'Amulet of strength',
                link: 'Amulet_of_strength',
                id: 1725,
                dropAmount: [1, 1],
                rarity: 2/21,
            },
            {
                name: 'Iron ore',
                link: 'Iron_ore',
                id: 440,
                dropAmount: [100, 100],
                rarity: 1/64,
            }, 
            {
                name: 'Mithril bar',
                link: 'Mithril_bar',
                id: 2359,
                dropAmount: [1, 1],
                rarity: 1/128,
            }, 
            {
                name: 'Yew logs',
                link: 'Yew_logs',
                id: 1515,
                dropAmount: [100, 100],
                rarity: 5/64,
            }, 
            {
                name: 'Shark',
                link: 'Shark',
                id: 385,
                dropAmount: [4, 4],
                rarity: 1/64,
            }, 
            {
                name: 'Oyster pearls',
                link: 'Oyster_pearls',
                id: 411,
                dropAmount: [1, 1],
                rarity: 1/128,
            }, 
            {
                name: 'Long bone',
                link: 'Long_bone',
                dropAmount: [1, 1],
                rarity: 1/400,
            }, 
            {
                name: `Baby mole`,
                link: `Baby_mole`,
                dropAmount: [1, 1],
                rarity: 1/3000,
            }, 
            {
                name: 'Clue scroll (elite)',
                link: 'Clue_scroll',
                dropAmount: [1, 1],
                rarity: 1/500,
            }, 
            {
                name: 'Curved bone',
                link: 'Curved_bone',
                dropAmount: [1, 1],
                rarity: 1/5000,
            },
        ]
    },
];