const enemies = [
    {
    name: 'General Graardor',
    killsph: 20,
    rolls: 2,
    drops: [
            {
                name: 'Big bones', 
                link: 'Big_bones',
                id: 532,
                dropAmount: [1, 1], 
                rarity: 100
            },
            {
                name: 'Rune 2h sword',
                link: 'Rune_2h_sword',
                id: 1319,
                dropAmount: [1, 1], 
                rarity: 2/21
            },
            {
                name: 'Rune pickaxe', 
                link: 'Rune_pickaxe', 
                id: 1275,
                dropAmount: [1, 1], 
                rarity: 2/21
            },
            {
                name: 'Rune longsword',
                link: 'Rune_longsword', 
                id: 1303,
                dropAmount: [1, 1],
                rarity: 2/21,
            },
            {
                name: 'Rune platebody',
                link: 'Rune_platebody', 
                id: 1127,
                dropAmount: [1, 1],
                rarity:  2/21,
            },
            {
                name: 'Bandos chestplate',
                link: 'Bandos_chestplate',
                id: 11832,
                dropAmount: [1, 1],
                rarity: 1/384,
            },
            {
                name: 'Bandos tassets',
                link: 'Bandos_tassets',
                id: 11834,
                dropAmount: [1, 1],
                rarity: 1/384,
            },
            {
                name: 'Bandos boots',
                link: 'Bandos_boots',
                id: 11836,
                dropAmount: [1, 1],
                rarity: 1/384,
            },
            {
                name: 'Nature rune',
                link: 'Nature_rune',
                id: 561,
                dropAmount: [40, 60],
                rarity: 1/25,
            }, 
            {
                name: 'Adamantite ore',
                link: 'Adamantite_ore',
                id: 449,
                dropAmount: [15, 20],
                rarity: 2/21,
            }, 
            {
                name: 'Coal',
                link: 'Coal',
                id: 453,
                dropAmount: [115, 120],
                rarity: 1/10,
            }, 
            {
                name: 'Coins',
                link: 'Coins',
                dropAmount: [19581, 21000],
                rarity: 1/10,
                price: 1,
            }, 
            {
                name: 'Snapdragon seed',
                link: 'Snapdragon_seed',
                id: 5300,
                dropAmount: [1, 1],
                rarity: 1/25,
            }, 
            {
                name: 'Magic log',
                link: 'Magic_log',
                id: 1513,
                dropAmount: [15, 20],
                rarity: 1/25,
            }, 
            {
                name: 'Super restore(4)',
                link: 'Super_restore4',
                id: 3024,
                dropAmount: [3, 3],
                rarity: 1/25,
            }, 
            {
                name: 'Grimy snapdragon',
                link: 'Grimy_snapdragon',
                id: 3051,
                dropAmount: [3, 3],
                rarity: 1/25,
            }, 
            {
                name: 'Clue scroll (elite)',
                link: 'Clue_scroll',
                dropAmount: [1, 1],
                rarity: 1/250,
            }, 
            {
                name: 'Godsword shard 1',
                link: 'Godsword_shard_1',
                id: 11818,
                dropAmount: [1, 1],
                rarity: 1/256,
            }, 
            {
                name: 'Godsword shard 2',
                link: 'Godsword_shard_2',
                id: 11820,
                dropAmount: [1, 1],
                rarity: 1/256,
            }, 
            {
                name: 'Godsword shard 3',
                link: 'Godsword_shard_3',
                id: 11822,
                dropAmount: [1, 1],
                rarity: 1/256,
            },
            {
                name: 'Long bone',
                link: 'Long_bone',
                dropAmount: [1, 1],
                rarity: 1/400,
            },
            {
                name: 'Bandos hilt',
                link: 'Bandos_hilt',
                id: 11812,
                dropAmount: [1, 1],
                rarity: 1/508,
            },
            {
                name: 'Pet general graardor',
                link: `Pet_general_graardor`,
                dropAmount: [1, 1],
                rarity: 1/5000,
            },
            {
                name: 'Rare drop table',
                link: 'Rare_drop_table',
                dropAmount: [1, 1],
                rarity: 1/127,
            },
        ]
    },
    {
    name: `Kree'arra`,
    killsph: 20,
    rolls: 3,
    drops: [
            {
                name: 'Big bones', 
                link: 'Big_bones',
                id: 532,
                dropAmount: [1, 1], 
                rarity: 100
            },
            {
                name: 'Feather', 
                link: 'Feather',
                id: 314,
                dropAmount: [1, 15], 
                rarity: 100
            },
            {
                name: 'Rune sword', 
                link: 'Rune_sword',
                id: 1289,
                dropAmount: [1, 1], 
                rarity: 1/406
            },
            {
                name: 'Rune crossbow', 
                link: 'Rune_croosbow',
                id: 9185,
                dropAmount: [1, 1], 
                rarity: 2/21
            },
            {
                name: `Black d'hide`,
                link: 'Black_dhide',
                id: 2503,
                dropAmount: [1, 1],
                rarity: 2/21,
            },
            {
                name: 'Armadyl helmet',
                link: 'Armadyl_helmet',
                id: 11826,
                dropAmount: [1, 1],
                rarity:  1/384,
            },
            {
                name: 'Armadyl chestplate',
                link: 'Armadyl_chestplate',
                id: 11828,
                dropAmount: [1, 1],
                rarity: 1/384,
            },
            {
                name: 'Armadyl chainskirt',
                link: 'Armadyl_chainskirt',
                id: 11830,
                dropAmount: [1, 1],
                rarity: 1/384,
            },
            {
                name: 'Bandos boots',
                link: 'Bandos_boots',
                id: 11836,
                dropAmount: [1, 1],
                rarity: 1/384,
            },
            {
                name: 'Runite bolts',
                link: 'Runite_bolts',
                id: 9144,
                dropAmount: [18, 25],
                rarity: 2/21,
            }, 
            {
                name: 'Mind rune',
                link: 'Mind_rune',
                id: 558,
                dropAmount: [500, 601],
                rarity: 1/64, 
            }, 
            {
                name: 'Rune arrow',
                link: 'Rune_arrow',
                id: 892,
                dropAmount: [100, 105],
                rarity: 1/64, 
            }, 
            {
                name: 'Dragonstone bolts(e)',
                link: 'Dragonstone_boltse',
                id: 9244,
                dropAmount: [5, 15],
                rarity: 1/64,
            }, 
            {
                name: 'Coins',
                link: 'Coins',
                dropAmount: [18000, 21000],
                rarity: 2/21,
                price: 1,
            }, 
            {
                name: 'Rare drop table',
                link: 'Rare_drop_table',
                dropAmount: [1, 1],
                rarity: 8/127,
            }, 
            {
                name: 'Dwarf weed',
                link: 'Dwarf_weed',
                id: 267,
                dropAmount: [5, 22],
                rarity: 2/21,
            }, 
            {
                name: 'Dwarf weed seed',
                link: 'Dwarf_weed_seed',
                id: 5303,
                dropAmount: [3, 3],
                rarity: 2/21,
            }, 
            {
                name: 'Ranging potion(3)',
                link: 'Ranging_potion',
                id: 169,
                dropAmount: [3, 3],
                rarity: 1/64,
            }, 
            {
                name: 'Super defence(3)',
                link: 'Super_defence',
                id: 163,
                dropAmount: [3, 3],
                rarity: 1/64,
            }, 
            {
                name: 'Crystal key',
                link: 'Crystal_key',
                id: 989,
                dropAmount: [3, 3],
                rarity: 1/64,
            }, 
            {
                name: 'Yew seed',
                link: 'Yew_seed',
                id: 5315,
                dropAmount: [1, 1],
                rarity: 1/128, 
            }, 
            {
                name: 'Clue scroll (elite)',
                link: 'Clue_scroll',
                dropAmount: [1, 1],
                rarity: 1/250,
            }, 
            {
                name: 'Godsword shard 1',
                link: 'Godsword_shard_1',
                id: 11818,
                dropAmount: [1, 1],
                rarity: 1/256,
            }, 
            {
                name: 'Godsword shard 2',
                link: 'Godsword_shard_2',
                id: 11820,
                dropAmount: [1, 1],
                rarity: 1/256,
            }, 
            {
                name: 'Godsword shard 3',
                link: 'Godsword_shard_3',
                id: 11822,
                dropAmount: [1, 1],
                rarity: 1/256,
            },
            {
                name: 'Long bone',
                link: 'Long_bone',
                dropAmount: [1, 1],
                rarity: 1/400,
            },
            {
                name: 'Armadyl hilt',
                link: 'Armadyl_hilt',
                id: 11810,
                dropAmount: [1, 1],
                rarity: 1/508,
            },
            {
                name: `Pet kree'arra`,
                link: `Pet_kreearra`,
                dropAmount: [1, 1],
                rarity: 1/5000,
            },
            {
                name: `Curved bone`,
                link: 'Curved_bone',
                dropAmount: [1, 1],
                rarity: 1/5000,
            },
        ]
    },
    {
    name: `Kril Tsutsaroth`,
    killsph: 20,
    rolls: 2,
    drops: [
            {
                name: 'Ashes', 
                link: `Ashes`,
                dropAmount: [1, 1], 
                rarity: 100,
                price: 1,
            },
            {
                name: 'Adamant arrow(p++)',
                link: 'Adamant_arrowp',
                id: 5626,
                dropAmount: [295, 300], 
                rarity: 2/21
            },
            {
                name: 'Rune scimitar',
                link: 'Rune_scimitar',
                id: 1333,
                dropAmount: [1, 1], 
                rarity: 1/64
            },
            {
                name: `Dragon dagger(p++)`,
                link: `Dragon_dagger`,
                id: 5698,
                dropAmount: [1, 1],
                rarity: 1/64,
            },
            {
                name: 'Steam battlestaff',
                link: 'Steam_battlestaff',
                id: 11787,
                dropAmount: [1, 1],
                rarity:  1/128,
            },
            {
                name: 'Zamorakian spear',
                link: 'Zamorakian_spear',
                id: 11824,
                dropAmount: [1, 1],
                rarity: 1/128,
            },
            {
                name: 'Rune sword',
                link: 'Rune_sword',
                id: 1289,
                dropAmount: [1, 1],
                rarity: 1/406,
            },
            {
                name: 'Staff of the dead',
                link: 'Staff_of_the_dead',
                id: 11791,
                dropAmount: [1, 1],
                rarity: 1/508,
            },
            {
                name: 'Rune platelegs',
                link: 'Rune_platelegs',
                id: 1079,
                dropAmount: [1, 1],
                rarity: 2/21,
            }, 
            {
                name: 'Adamant platebody',
                link: 'Adamant_platebody',
                id: 1123,
                dropAmount: [1, 1],
                rarity: 2/21,
            }, 
            {
                name: 'Super attack(3)',
                link: 'Super_attack',
                id: 145,
                dropAmount: [3, 3],
                rarity: 2/21,
            }, 
            {
                name: 'Super strength(3)',
                link: 'Super_strength',
                id: 157,
                dropAmount: [3, 3],
                rarity: 2/21,
            }, 
            {
                name: 'Super restore(3)',
                link: 'Super_restore',
                id: 3026,
                dropAmount: [3, 3],
                rarity: 2/21,
            }, 
            {
                name: 'Zamorak brew(3)',
                link: 'Zamorak_brew',
                id: 189,
                dropAmount: [3, 3],
                rarity: 2/21,
            }, 
            {
                name: 'Death rune',
                link: 'Death_rune',
                id: 560,
                dropAmount: [120, 125],
                rarity: 2/21,
            }, 
            {
                name: 'Coins',
                link: 'Coins',
                dropAmount: [19362, 20073],
                rarity: 2/21,
                price: 1,
            }, 
            {
                name: 'Rare drop table',
                link: 'Rare_drop_table',
                dropAmount: [1, 1],
                rarity: 8/127,
            }, 
            {
                name: 'Blood rune',
                link: 'Blood_rune',
                id: 565,
                dropAmount: [80, 90],
                rarity: 1/64,
            }, 
            {
                name: 'Grimy lantadyme',
                link: 'Grimy_lantadyme',
                id: 2485,
                dropAmount: [7, 13],
                rarity: 1/64,
            }, 
            {
                name: 'Lantadyme seed',
                link: 'Lantadyme_seed',
                id: 5302,
                dropAmount: [3, 3],
                rarity: 1/64, 
            }, 
            {
                name: 'Clue scroll (elite)',
                link: 'Clue_scroll',
                dropAmount: [1, 1],
                rarity: 1/250,
            }, 
            {
                name: 'Godsword shard 1',
                link: 'Godsword_shard_1',
                id: 11818,
                dropAmount: [1, 1],
                rarity: 1/256,
            }, 
            {
                name: 'Godsword shard 2',
                link: 'Godsword_shard_2',
                id: 11820,
                dropAmount: [1, 1],
                rarity: 1/256,
            }, 
            {
                name: 'Godsword shard 3',
                link: 'Godsword_shard_3',
                id: 11822,
                dropAmount: [1, 1],
                rarity: 1/256,
            },
            {
                name: 'Long bone',
                link: 'Long_bone',
                dropAmount: [1, 1],
                rarity: 1/400,
            },
            {
                name: 'Zamorak hilt',
                link: 'Zamorak_hilt',
                id: 11816,
                dropAmount: [1, 1],
                rarity: 1/508,
            },
            {
                name: `Pet k'ril tsutsaroth`,
                link: `Pet_kril_tsutsaroth`,
                dropAmount: [1, 1],
                rarity: 1/5000,
            },
            {
                name: `Curved bone`,
                link: 'Curved_bone',
                dropAmount: [1, 1],
                rarity: 1/5000,
            },
        ]
    },
    {
    name: `Commander Zilyana`,
    killsph: 20,
    rolls: 2,
    drops: [
            {
                name: 'Bones',
                link: 'Bones',
                id: 526,
                dropAmount: [1, 1], 
                rarity: 100
            },
            {
                name: 'Saradomin sword',
                link: 'Saradomin_sword',
                id: 11838,
                dropAmount: [1, 1], 
                rarity: 1/127
            },
            {
                name: 'Armadyl crossbow', 
                link: 'Armadyl_crossbow', 
                id: 11785,
                dropAmount: [1, 1], 
                rarity: 1/508
            },
            {
                name: `Rune sword`,
                link: `Rune_sword`,
                id: 1289,
                dropAmount: [1, 1],
                rarity: 1/406,
            },
            {
                name: 'Rune dart',
                link: `Rune_dart`,
                id: 811,
                dropAmount: [35, 40],
                rarity:  2/21,
            },
            {
                name: 'Law rune',
                link: 'Law_rune',
                id: 563,
                dropAmount: [95, 105],
                rarity: 2/21,
            },
            {
                name: 'Rune plateskirt',
                link: 'Rune_plateskirt',
                id: 1093,
                dropAmount: [1, 1],
                rarity: 2/21,
            },
            {
                name: 'Adamant platebody',
                link: 'Adamant_platebody',
                id: 1123,
                dropAmount: [1, 1],
                rarity: 1/64,
            },
            {
                name: 'Rune kiteshield',
                link: 'Rune_kiteshield',
                id: 1201,
                dropAmount: [1, 1],
                rarity: 1/64,
            }, 
            {
                name: 'Grimy ranarr weed',
                link: 'Grimy_ranarr_weed',
                id: 207,
                dropAmount: [5, 5],
                rarity: 2/21,
            }, 
            {
                name: 'Ranarr seed',
                link: 'Ranarr_seed',
                id: 5295,
                dropAmount: [2, 2],
                rarity: 2/21,
            }, 
            {
                name: 'Prayer potion(4)',
                link: 'Prayer_potion',
                id: 2434,
                dropAmount: [3, 3],
                rarity: 8/127,
            }, 
            {
                name: 'Saradomin brew(3)',
                link: 'Saradomin_brew',
                id: 6687,
                dropAmount: [3, 3],
                rarity: 6/127,
            }, 
            {
                name: 'Super restore(4)',
                link: 'Super_restore',
                id: 3024,
                dropAmount: [3, 3],
                rarity: 6/127,
            },
            {
                name: 'Super defence(4)',
                link: 'Super_defence',
                id: 2442,
                dropAmount: [3, 3],
                rarity: 6/127,
            }, 
            {
                name: 'Magic potion(3)',
                name: 'Magic_potion',
                id: 3042,
                dropAmount: [3, 3],
                rarity: 6/127,
            }, 
            {
                name: 'Magic seed',
                link: 'Magic_seed',
                id: 5316,
                dropAmount: [1, 1],
                rarity: 1/128,
            }, 
            {
                name: 'Coins',
                link: 'Coins',
                dropAmount: [19362, 20073],
                rarity: 2/21,
                price: 1,
            }, 
            {
                name: 'Diamond',
                link: 'Diamond',
                id: 1601,
                dropAmount: [6, 6],
                rarity: 1/64,
            }, 
            {
                name: 'Rare drop table',
                link: 'Rare_drop_table',
                dropAmount: [1, 1],
                rarity: 8/127,
            }, 
            {
                name: `Saradomin's light`,
                link: `Saradomins_light`,
                id: 13256,
                dropAmount: [1, 1],
                rarity: 1/254,
            }, 
            {
                name: 'Clue scroll (elite)',
                link: 'Clue_scroll',
                dropAmount: [1, 1],
                rarity: 1/250,
            }, 
            {
                name: 'Godsword shard 1',
                link: 'Godsword_shard_1',
                id: 11818,
                dropAmount: [1, 1],
                rarity: 1/256,
            }, 
            {
                name: 'Godsword shard 2',
                link: 'Godsword_shard_2',
                id: 11820,
                dropAmount: [1, 1],
                rarity: 1/256,
            }, 
            {
                name: 'Godsword shard 3',
                link: 'Godsword_shard_3',
                id: 11822,
                dropAmount: [1, 1],
                rarity: 1/256,
            },
            {
                name: 'Saradomin hilt',
                link: 'Saradomin_hilt',
                id: 11814,
                dropAmount: [1, 1],
                rarity: 1/508,
            },
            {
                name: `Pet zilyana`,
                link: `Pet_zilyana`,
                dropAmount: [1, 1],
                rarity: 1/5000,
            },
        ]
    },
    {
    name: `Giant Mole`,
    killsph: 20,
    rolls: 4,
    drops: [
            {
                name: 'Big bones', 
                link: 'Big_bones', 
                id: 532,
                dropAmount: [1, 1], 
                rarity: 100
            },
            {
                name: 'Mole claw', 
                link: 'Mole_claw', 
                id: 7416,
                dropAmount: [1, 1], 
                rarity: 100
            },
            {
                name: 'Mole skin', 
                link: 'Mole_skin',
                id: 7418,
                dropAmount: [1, 3], 
                rarity: 100
            },
            {
                name: 'Air rune',
                link: 'Air_rune',
                id: 556,
                dropAmount: [105, 105], 
                rarity: 2/21
            },
            {
                name: `Fire rune`,
                link: 'Fire_rune',
                id: 554,
                dropAmount: [105, 105],
                rarity: 2/21,
            },
            {
                name: 'Blood rune',
                link: 'Blood_rune',
                id: 565,
                dropAmount: [15, 15],
                rarity:  2/21,
            },
            {
                name: 'Death rune',
                link: 'Death_rune',
                id: 560,
                dropAmount: [7, 7],
                rarity: 1/128,
            },
            {
                name: 'Law rune',
                link: 'Law_rune',
                id: 563,
                dropAmount: [15, 15],
                rarity: 1/64,
            },
            {
                name: 'Iron arrow',
                link: 'Iron_arrow',
                id: 884,
                dropAmount: [690, 690],
                rarity: 1/64,
            },
            {
                name: 'Adamant longsword',
                link: 'Adamant_longsword',
                id: 1301,
                dropAmount: [1, 1],
                rarity: 2/21,
            }, 
            {
                name: 'Mithril axe',
                link: 'Mithril_axe',
                id: 1355,
                dropAmount: [1, 1],
                rarity: 2/21,
            }, 
            {
                name: 'Mithril battleaxe',
                link: 'Mithril_battleaxe',
                id: 1369,
                dropAmount: [1, 1],
                rarity: 2/21,
            }, 
            {
                name: 'Mithril platebody',
                link: 'Mithril_platebody',
                id: 1121,
                dropAmount: [1, 1],
                rarity: 2/21,
            }, 
            {
                name: 'Rune med helm',
                link: 'Rune_med_helm',
                id: 1147,
                dropAmount: [1, 1],
                rarity: 1/64,
            }, 
            {
                name: 'Amulet of strength',
                link: 'Amulet_of_strength',
                id: 1725,
                dropAmount: [1, 1],
                rarity: 2/21,
            },
            {
                name: 'Iron ore',
                link: 'Iron_ore',
                id: 440,
                dropAmount: [100, 100],
                rarity: 1/64,
            }, 
            {
                name: 'Mithril bar',
                link: 'Mithril_bar',
                id: 2359,
                dropAmount: [1, 1],
                rarity: 1/128,
            }, 
            {
                name: 'Yew logs',
                link: 'Yew_logs',
                id: 1515,
                dropAmount: [100, 100],
                rarity: 5/64,
            }, 
            {
                name: 'Shark',
                link: 'Shark',
                id: 385,
                dropAmount: [4, 4],
                rarity: 1/64,
            }, 
            {
                name: 'Oyster pearls',
                link: 'Oyster_pearls',
                id: 411,
                dropAmount: [1, 1],
                rarity: 1/128,
            }, 
            {
                name: 'Long bone',
                link: 'Long_bone',
                dropAmount: [1, 1],
                rarity: 1/400,
            }, 
            {
                name: `Baby mole`,
                link: `Baby_mole`,
                dropAmount: [1, 1],
                rarity: 1/3000,
            }, 
            {
                name: 'Clue scroll (elite)',
                link: 'Clue_scroll',
                dropAmount: [1, 1],
                rarity: 1/500,
            }, 
            {
                name: 'Curved bone',
                link: 'Curved_bone',
                dropAmount: [1, 1],
                rarity: 1/5000,
            },
        ]
    },
//    {
//    name: `King Black Dragon`,
//    killsph: 20,
//    rolls: 3,
//    drops: [
//            {
//                name: `Dragon bones`,
//                link: `Dragon_bones`,
//                dropAmount: [1, 1],
//                rarity: 100,
//            }, 
//            {
//                name: `Black dragonhide`,
//                link: `Black_dragonhide`,
//                id: 1747,
//                dropAmount: [2, 2],
//                rarity: 100,
//            }, 
//            {
//                name: `Draconic visage`,
//                link: `Draconic_visage`,
//                id: 11286,
//                dropAmount: [1, 1],
//                rarity: 1/5000,
//            },
//            {
//                name: `Prince black dragon`,
//                link: `Prince_black_dragon`,
//                dropAmount: [1, 1],
//                rarity: 1/3000,
//            },
//            {
//                name: `Dragon pickaxe`,
//                link: `Dragon_pickaxe`,
//                id: 11920,
//                dropAmount: [1, 1],
//                rarity: 1/1500,
//            },
//            {
//                name: `Clue scroll (elite)`,
//                link: `Clue_scroll`,
//                dropAmount: [1, 1],
//                rarity: 1/450,
//            },
//            {
//                name: `Kbd heads`,
//                link: `Kbd_heads`,
//                dropAmount: [1, 1],
//                rarity: 1/128,
//            },
//            {
//                name: `Dragon med helm`,
//                link: `Dragon_med_helm`,
//                id: 1149,
//                dropAmount: [1, 1],
//                rarity: 1/128,
//            },
//            {
//                name: `Runite bar`,
//                link: `Runite_bar`,
//                id: 2363,
//                dropAmount: [1, 1],
//                rarity: 1/64,
//            },
//            {
//                name: `Runite limbs`,
//                link: `Runite_limbs`,
//                id: 9431,
//                dropAmount: [1, 1],
//                rarity: 1/64,
//            },
//            {
//                name: `Adamantite bar`,
//                link: `Adamantite_bar`,
//                id: 2361,
//                dropAmount: [3, 3],
//                rarity: 1/64,
//            }, 	 	    	
//            {
//                name: `Gold ore`,
//                link: `Gold_ore`,
//                id: 444,
//                dropAmount: [100, 100],
//                rarity: 1/64,
//            },
//            {
//                name: `Shark`,
//                link: `Shark`,
//                id: 6969,
//                dropAmount: [4, 4],
//                rarity: 1/64,
//            },
//            {
//                name: `Dragon javelin heads`,
//                link: `Dragon_javelin_heads`,
//                id: 19582,
//                dropAmount: [15, 15],
//                rarity: 1/64,
//            },
//            {
//                name: `Dragon arrowtips`,
//                link: `Dragon_arrowtips`,
//                id: 11237,
//                dropAmount: [5, 14],
//                rarity: 1/64,
//            },
//            {
//                name: `Dragon dart tip`,
//                link: `Dragon_dart_tip`,
//                id: 11232,
//                dropAmount: [5, 14],
//                rarity: 1/64,
//            },
//            {
//                name: `Runite bolts`,
//                link: `Runite_bolts`,
//                id: 9144,
//                dropAmount: [10, 25],
//                rarity: 1/64,
//            },
//            {
//                name: `Adamant kiteshield`,
//                link: `Adamant_kiteshield`,
//                id: 1199,
//                dropAmount: [1, 1],
//                rarity: 1/64,
//            },
//            {
//                name: `Iron arrow`,
//                link: `Iron_arrow`,
//                id: 11701,
//                dropAmount: [690, 690],
//                rarity: 1/64,
//            },
//            {
//                name: `Rare drop table`,
//                link: `Rare_drop_table`,
//                dropAmount: [1, 1],
//                rarity: 1/16,
//            },
//            {
//                name: `Yew log`,
//                link: `Yew_log`,
//                id: 1515,
//                dropAmount: [150, 150],
//                rarity: 1/16,
//            },
//            {
//                name: `Rune longsword`,
//                link: `Rune_longsword`,
//                id: 1303,
//                dropAmount: [1, 1],
//                rarity: 1/16,
//            },
//            {
//                name: `Adamant platebody`,
//                link: `Adamant_platebody`,
//                id: 1123,
//                dropAmount: [1, 1],
//                rarity: 1/16,
//            },
//            {
//                name: `Amulet of power`,
//                link: `Amulet_of_power`,
//                id: 1731,
//                dropAmount: [1, 1],
//                rarity: 1/16,
//            },
//            {
//                name: `Fire rune`,
//                link: `Fire_rune`,
//                id: 554,
//                dropAmount: [300, 300],
//                rarity: 1/16,
//            },
//            {
//                name: `Air rune`,
//                link: `Air_rune`,
//                id: 556,
//                dropAmount: [300, 300],
//                rarity: 1/16,
//            },
//            {
//                name: `Blood rune`,
//                link: `Blood_rune`,
//                id: 565,
//                dropAmount: [300, 300],
//                rarity: 1/16,
//            },
//            {
//                name: `Law rune`,
//                link: `Law_rune`,
//                id: 563,
//                dropAmount: [300, 300],
//                rarity: 1/16,
//            },
//        ]
//    },
//    {
//    name: `Vet'ion`,
//    killsph: 20,
//    rolls: 3,
//    drops: [
//            {
//                name: `Big bones`,
//                link: `Big_bones`,
//                dropAmount: [1, 1],
//                rarity: 100,
//            },
//            {
//                name: `Skeleton champion scroll`,
//                link: `Skeleton_champion_scroll`,
//                dropAmount: [1, 1],
//                rarity: 1/5000,
//            },
//            {
//                name: `Curved bone`,
//                link: `Curved_bone`,
//                dropAmount: [1, 1],
//                rarity: 1/5000,
//            },
//            {
//                name: `Vet'ion jr.`,
//                link: `Vetion_jr`,
//                dropAmount: [1, 1],
//                rarity: 1/2000,
//            },   
//            {
//                name: `Ring of the gods`,
//                link: `Ring_of_the_gods`,
//                id: 12601,
//                dropAmount: [1, 1],
//                rarity: 1/512,
//            },
//            {
//                name: `Long bone`,
//                link: `Long_bone`,
//                dropAmount: [1, 1],
//                rarity: 1/400,
//            },
//            {
//                name: `Dragon 2h sword`,
//                link: `Dragon_h_sword`,
//                id: 7158,
//                dropAmount: [1, 1],
//                rarity: 1/256,
//            },
//            {
//                name: `Dragon pickaxe`,
//                link: `Dragon_pickaxe`,
//                id: 11920,
//                dropAmount: [1, 1],
//                rarity: 1/171,
//            },
//            {
//                name: `Rune 2h sword`,
//                link: `Rune_h_sword`,
//                id: 1319,
//                dropAmount: [1, 1],
//                rarity: 1/128,
//            },
//            {
//                name: `Long bone`,
//                link: `Long_bone`,
//                dropAmount: [1, 1],
//                rarity: 1/128,
//            },
//            {
//                name: `Grimy ranarr weed`,
//                link: `Grimy_ranarr_weed`,
//                id: 207,
//                dropAmount: [100, 100],
//                rarity: 1/128,
//            },
//            {
//                name: `Magic seed`,
//                link: `Magic_seed`,
//                id: 5316,
//                dropAmount: [1, 1],
//                rarity: 1/128,
//            },
//            {
//                name: `Clue scroll (elite)`,
//                link: `Clue_scroll`,
//                dropAmount: [1, 1],
//                rarity: 1/100,
//            },
//            {
//                name: `Dark fishing bait`,
//                link: `Dark_fishing_bait`,
//                id: 11940,
//                dropAmount: [375, 375],
//                rarity: 1/100,
//            },
//            {
//                name: `Mort myre fungus`,
//                link: `Mort_myre_fungus`,
//                id: 2970,
//                dropAmount: [200, 200],
//                rarity: 1/100,
//            },
//            {
//                name: `Yew seed`,
//                link: `Yew_seed`,
//                id: 5315,
//                dropAmount: [1, 1],
//                rarity: 1/100,
//            },
//            {
//                name: `Palm tree seed`,
//                link: `Palm_tree_seed`,
//                id: 5289,
//                dropAmount: [1, 1],
//                rarity: 1/100,
//            },
//            {
//                name: `Cannonball`,
//                link: `Cannonball`,
//                id: 2,
//                dropAmount: [250, 250],
//                rarity: 1/100,
//            },
//            {
//                name: `Supercompost`,
//                link: `Supercompost`,
//                id: 6034,
//                dropAmount: [100, 100],
//                rarity: 1/30,
//            },
//            {
//                name: `Oak plank`,
//                link: `Oak_plank`,
//                id: 8778,
//                dropAmount: [300, 300],
//                rarity: 1/30,
//            },
//            {
//                name: `Uncut dragonstone`,
//                link: `Uncut_dragonstone`,
//                id: 1631,
//                dropAmount: [300, 300],
//                rarity: 1/30,
//            },
//            {
//                name: `Dragon bones`,
//                link: `Dragon_bones`,
//                id: 536,
//                dropAmount: [100, 100],
//                rarity: 1/30,
//            },
//            {
//                name: `Gold ore`,
//                link: `Gold_ore`,
//                id: 444,
//                dropAmount: [300, 300],
//                rarity: 1/30,
//            },
//            {
//                name: `Magic logs`,
//                link: `Magic_logs`,
//                id: 1513,
//                dropAmount: [100, 100],
//                rarity: 1/30,
//            },
//            {
//                name: `Sanfew serum(4)`,
//                link: `Sanfew_serum`,
//                id: 10925,
//                dropAmount: [10, 10],
//                rarity: 1/30,
//            },
//            {
//                name: `Blood rune`,
//                link: `Blood_rune`,
//                id: 565,
//                dropAmount: [200, 200],
//                rarity: 1/30,
//            },
//            {
//                name: `Death rune`,
//                link: `Death_rune`,
//                id: 560,
//                dropAmount: [200, 200],
//                rarity: 1/30,
//            },
//            {
//                name: `Chaos rune`,
//                link: `Chaos_rune`,
//                id: 11694,
//                dropAmount: [400, 400],
//                rarity: 1/30,
//            },
//            {
//                name: `Ancient staff`,
//                link: `Ancient_staff`,
//                id: 4675,
//                dropAmount: [400, 400],
//                rarity: 1/30,
//            },
//            {
//                name: `Rune pickaxe`,
//                link: `Rune_pickaxe`,
//                id: 1275,
//                dropAmount: [1, 1],
//                rarity: 1/16,
//            },
//            {
//                name: `Uncut diamond`,
//                link: `Uncut_diamond`,
//                id: 1617,
//                dropAmount: [10, 10],
//                rarity: 1/16,
//            },
//            {
//                name: `Uncut ruby`,
//                link: `Uncut_ruby`,
//                id: 1619,
//                dropAmount: [20, 20],
//                rarity: 1/16,
//            },
//            {
//                name: `Limpwurt root`,
//                link: `Limpwurt_root`,
//                id: 225,
//                dropAmount: [50, 50],
//                rarity: 1/16,
//            },
//            {
//                name: `Ogre coffin key`,
//                link: `Ogre_coffin_key`,
//                id: 4850,
//                dropAmount: [10, 10],
//                rarity: 1/16,
//            },
//            {
//                name: `Coins`,
//                link: `Coins`,
//                dropAmount: [15000, 20000],
//                rarity: 1/16,
//            },
//            {
//                name: `Super restore(4)`,
//                link: `Super_restore`,
//                id: 3024,
//                dropAmount: [3, 3],
//                rarity: 1/16,
//            },
//            {
//                name: `Dark crab`,
//                link: `Dark_crab`,
//                id: 11936,
//                dropAmount: [8, 8],
//                rarity: 1/16,
//            },
//        ]
//    },
//    {
//    name: `Crazy archaeologist`,
//    killsph: 20,
//    rolls: 3,
//    drops: [
//            {
//                name: `Bones`,
//                link: `Bones`,
//                price: 0,
//                dropAmount: [1, 1],
//                rarity: 100,
//            },
//            {
//                name: `Malediction shard 2`,
//                link: `Malediction_shard`,
//                id: 11931,
//                dropAmount: [1, 1],
//                rarity: 1/256,
//            },
//            {
//                name: `Odium shard 2`,
//                link: `Odium_shard`,
//                id: 11929,
//                dropAmount: [1, 1],
//                rarity: 1/256,
//            },
//            {
//                name: `Dragon arrow`,
//                link: `Dragon_arrow`,
//                id: 11212,
//                dropAmount: [75, 75],
//                rarity: 1/128,
//            },
//            {
//                name: `Fedora`,
//                link: `Fedora`,
//                id: 11990,
//                dropAmount: [1, 1],
//                rarity: 1/128,
//            },
//            {
//                name: `Clue scroll (hard)`,
//                link: `Clue_scroll`,
//                dropAmount: [1, 1],
//                rarity: 1/128,
//            },
//            {
//                name: `Long bone`,
//                link: `Long_bone`,
//                dropAmount: [1, 1],
//                rarity: 1/128,
//            },
//            {
//                name: `Onyx bolt tips`,
//                link: `Onyx_bolt_tips`,
//                id: 9194,
//                dropAmount: [12, 12],
//                rarity: 5/128,
//            },
//            {
//                name: `White berries`,
//                link: `White_berries`,
//                id: 239,
//                dropAmount: [10, 10],
//                rarity: 5/128,
//            },
//            {
//                name: `Red dragonhide`,
//                link: `Red_dragonhide`,
//                id: 1749,
//                dropAmount: [10, 10],
//                rarity: 5/128,
//            },
//            {
//                name: `Muddy key`,
//                link: `Muddy_key`,
//                id: 991,
//                dropAmount: [10, 10],
//                rarity: 5/128,
//            },
//            {
//                name: `Cannonball`,
//                link: `Cannonball`,
//                id: 2,
//                dropAmount: [150, 150],
//                rarity: 5/128,
//            },
//            {
//                name: `Rune crossbow`,
//                link: `Rune_crossbow`,
//                id: 9185,
//                dropAmount: [1, 1],
//                rarity: 5/128,
//            },
//            {
//                name: `Rune knife`,
//                link: `Rune_knife`,
//                id: 868,
//                dropAmount: [1, 1],
//                rarity: 5/128,
//            },
//            {
//                name: `Red d'hide body`,
//                link: `Red_dhide_body`,
//                id: 2501,
//                dropAmount: [1, 1],
//                rarity: 5/128,
//            },
//            {
//                name: `Mud rune`,
//                link: `Mud_rune`,
//                id: 4698,
//                dropAmount: [1, 1],
//                rarity: 5/128,
//            },
//            {
//                name: `Coins`,
//                link: `Coins`,
//                dropAmount: [522, 4000],
//                rarity: 1/16,
//            },
//            {
//                name: `Uncut emerald`,
//                link: `Uncut_emerald`,
//                id: 1621,
//                dropAmount: [6, 6],
//                rarity: 1/16,
//            },
//            {
//                name: `Uncut sapphire`,
//                link: `Uncut_sapphire`,
//                id: 1623,
//                dropAmount: [4, 4],
//                rarity: 1/16,
//            },
//            {
//                name: `Rusty sword`,
//                link: `Rusty_sword`,
//                id: 686,
//                dropAmount: [1, 1],
//                rarity: 1/16,
//            },
//            {
//                name: `Silver ore`,
//                link: `Silver_ore`,
//                id: 442,
//                dropAmount: [40, 40],
//                rarity: 1/16,
//            },
//            {
//                name: `Prayer potion(4)`,
//                link: `Prayer_potion`,
//                id: 2434,
//                dropAmount: [1, 1],
//                rarity: 1/16,
//            },
//            {
//                name: `Potato with cheese`,
//                link: `Potato_with_cheese`,
//                id: 6705,
//                dropAmount: [3, 3],
//                rarity: 1/16,
//            },
//            {
//                name: `Anchovy pizza`,
//                link: `Anchovy_pizza`,
//                id: 2297,
//                dropAmount: [8, 8],
//                rarity: 1/16,
//            },
//            {
//                name: `Shark`,
//                link: `Shark`,
//                id: 6969,
//                dropAmount: [1, 1],
//                rarity: 1/16,
//            },
//            {
//                name: `Grimy dwarf weed`,
//                link: `Grimy_dwarf_weed`,
//                id: 217,
//                dropAmount: [4, 4],
//                rarity: 1/16,
//            },
//        ]
//    },
//    {
//    name: `Zulrah`,
//    killsph: 20,
//    rolls: 3,
//    drops: [
//            {
//                name: `Zulrah's scales`,
//                link: `Zulrahs_scales`,
//                id: 12934,
//                dropAmount: [100, 300],
//                rarity: 100, 
//            },
//            {
//                name: `Magma mutagen`,
//                link: `Magma_mutagen`,
//                dropAmount: [1, 1],
//                rarity: 1/6553.6, 
//            },
//            {
//                name: `Tanzanite mutagen`,
//                link: `Tanzanite_mutagen`,
//                dropAmount: [1, 1],
//                rarity: 1/6553.6, 
//            },
//            {
//                name: `Pet snakeling`,
//                link: `Pet_snakeling`,
//                dropAmount: [1, 1],
//                rarity: 1/4000, 
//            },
//            {
//                name: `Jar of swamp`,
//                link: `Jar_of_swamp`,
//                id: 12936,
//                dropAmount: [1, 1],
//                rarity: 1/3000, 
//            },
//            {
//                name: `Tanzanite fang`,
//                link: `Tanzanite_fang`,
//                id: 12922,
//                dropAmount: [1, 1],
//                rarity: 1/512, 
//            },
//            {
//                name: `Magic fang`,
//                link: `Magic_fang`,
//                id: 12932,
//                dropAmount: [1, 1],
//                rarity: 1/512, 
//            },
//            {
//                name: `Serpentine visage`,
//                link: `Serpentine_visage`,
//                id: 12927,
//                dropAmount: [1, 1],
//                rarity: 1/512, 
//            },
//            {
//                name: `Uncut onyx`,
//                link: `Uncut_onyx`,
//                id: 6571,
//                dropAmount: [1, 1],
//                rarity: 1/512, 
//            },
//            {
//                name: `Crystal seed`,
//                link: `Crystal_seed`,
//                id: 4207,
//                dropAmount: [1, 1],
//                rarity: 1/256, 
//            },
//            {
//                name: `Spirit seed`,
//                link: `Spirit_seed`,
//                dropAmount: [1, 1],
//                rarity: 1/256, 
//            },
//            {
//                name: `Dragon med helm`,
//                link: `Dragon_med_helm`,
//                id: 1149,
//                dropAmount: [1, 1],
//                rarity: 1/256, 
//            },
//            {
//                name: `Dragon halberd`,
//                link: `Dragon_halberd`,
//                id: 3204,
//                dropAmount: [1, 1],
//                rarity: 1/256, 
//            },
//            {
//                name: `Torstol seed`,
//                link: `Torstol_seed`,
//                id: 5304,
//                dropAmount: [1, 1],
//                rarity: 1/128, 
//            },
//            {
//                name: `Dwarf weed seed`,
//                link: `Dwarf_weed_seed`,
//                id: 5303,
//                dropAmount: [2, 2],
//                rarity: 1/128, 
//            },
//            {
//                name: `Snapdragon seed`,
//                link: `Snapdragon_seed`,
//                id: 5300,
//                dropAmount: [1, 1],
//                rarity: 1/128, 
//            },
//            {
//                name: `Toadflax seed`,
//                link: `Toadflax_seed`,
//                id: 5296,
//                dropAmount: [2, 2],
//                rarity: 1/128, 
//            },
//            {
//                name: `Toadflax`,
//                link: `Toadflax`,
//                id: 2998,
//                dropAmount: [10, 10],
//                rarity: 1/128, 
//            },
//            {
//                name: `Snapdragon`,
//                link: `Snapdragon`,
//                id: 3000,
//                dropAmount: [10, 10],
//                rarity: 1/128, 
//            },
//            {
//                name: `Dwarf weed`,
//                link: `Dwarf_weed`,
//                id: 267,
//                dropAmount: [30, 30],
//                rarity: 1/128, 
//            },
//            {
//                name: `Torstol`,
//                link: `Torstol`,
//                id: 269,
//                dropAmount: [10, 10],
//                rarity: 1/128, 
//            },
//            {
//                name: `Clue scroll (elite)`,
//                link: `Clue_scroll`,
//                dropAmount: [2, 2],
//                rarity: 1/75, 
//            },
//            {
//                name: `Magic seed`,
//                link: `Magic_seed`,
//                id: 5316,
//                dropAmount: [1, 1],
//                rarity: 1/64, 
//            },
//            {
//                name: `Papaya tree seed`,
//                link: `Papaya_tree_seed`,
//                id: 5288,
//                dropAmount: [3, 3],
//                rarity: 1/64, 
//            },
//            {
//                name: `Palm tree seed`,
//                link: `Palm_tree_seed`,
//                id: 5289,
//                dropAmount: [1, 1],
//                rarity: 1/64,
//            },
//            {
//                name: `Calquat tree seed`,
//                link: `Calquat_tree_seed`,
//                id: 5290,
//                dropAmount: [2, 2],
//                rarity: 1/64, 
//            },
//            {
//                name: `Runite ore`,
//                link: `Runite_ore`,
//                id: 451,
//                dropAmount: [2, 2],
//                rarity: 1/64, 
//            },
//            {
//                name: `Coal`,
//                link: `Coal`,
//                id: 453,
//                dropAmount: [200, 200],
//                rarity: 1/64, 
//            },
//            {
//                name: `Mahogany logs`,
//                link: `Mahogany_logs`,
//                id: 6332,
//                dropAmount: [50, 50],
//                rarity: 1/64, 
//            },
//            {
//                name: `Pure essence`,
//                link: `Pure_essence`,
//                id: 7936,
//                dropAmount: [1500, 1500],
//                rarity: 1/64, 
//            },
//            {
//                name: `Chaos rune`,
//                link: `Chaos_rune`,
//                id: 11694,
//                dropAmount: [500, 500],
//                rarity: 1/64, 
//            },
//            {
//                name: `Death rune`,
//                link: `Death_rune`,
//                id: 560,
//                dropAmount: [500, 500],
//                rarity: 1/64, 
//            },
//            {
//                name: `Yew log`,
//                link: `Yew_log`,
//                id: 1515,
//                dropAmount: [35, 35],
//                rarity: 1/16, 
//            },
//            {
//                name: `Dragonstone bolt tips`,
//                link: `Dragonstone_bolt_tips`,
//                id: 9193,
//                dropAmount: [12, 12],
//                rarity: 1/16, 
//            },
//            {
//                name: `Snakeskin`,
//                link: `Snakeskin`,
//                id: 6289,
//                dropAmount: [35, 35],
//                rarity: 1/16, 
//            },
//            {
//                name: `Flax`,
//                link: `Flax`,
//                id: 1779,
//                dropAmount: [1000, 1000],
//                rarity: 1/16, 
//            },
//            {
//                name: `Law rune`,
//                link: `Law_rune`,
//                id: 563,
//                dropAmount: [200, 200],
//                rarity: 1/16, 
//            },
//        ]
//    }
]